import { db } from "../db";

export async function dashboardStats() {
  const now = new Date();
  const [
    users,
    blockedUsers,
    cards,
    albums,
    forSale,
    activeAuctions,
    endedAuctions,
    bids,
    openNegotiations,
    orders,
    suggestions,
    complaints,
    openContacts,
    pendingSellers,
    paymentsToReview,
    disputes,
    payouts,
    fees,
  ] = await Promise.all([
    db.user.count({ where: { status: { not: "DELETED" } } }),
    db.user.count({ where: { status: "BLOCKED" } }),
    db.card.count({ where: { status: { not: "REMOVED" } } }),
    db.album.count(),
    db.listing.count({ where: { status: "ACTIVE", type: { in: ["DIRECT_SALE", "NEGOTIATION"] } } }),
    db.auction.count({ where: { status: { in: ["ACTIVE", "SCHEDULED"] }, endsAt: { gt: now } } }),
    db.auction.count({ where: { status: "ENDED" } }),
    db.bid.count(),
    db.negotiation.count({ where: { status: "OPEN" } }),
    db.order.aggregate({ _count: true, _sum: { amountCents: true } }),
    db.contactMessage.count({ where: { type: "SUGGESTION" } }),
    db.contactMessage.count({ where: { type: "COMPLAINT" } }),
    db.contactMessage.count({ where: { status: { in: ["OPEN", "IN_REVIEW"] } } }),
    db.sellerApplication.count({ where: { status: "PENDING" } }),
    db.order.count({ where: { status: "PAYMENT_REVIEW" } }),
    db.order.count({ where: { status: "DISPUTED" } }),
    db.order.aggregate({ where: { payoutStatus: "PENDING" }, _sum: { sellerNetCents: true }, _count: true }),
    db.order.aggregate({ where: { status: { in: ["DELIVERED", "COMPLETED"] } }, _sum: { feeCents: true } }),
  ]);
  return {
    users,
    blockedUsers,
    cards,
    albums,
    forSale,
    activeAuctions,
    endedAuctions,
    bids,
    openNegotiations,
    orders: orders._count,
    gmvCents: orders._sum.amountCents ?? 0,
    suggestions,
    complaints,
    openContacts,
    pendingSellers,
    paymentsToReview,
    disputes,
    payoutsCount: payouts._count,
    payoutsCents: payouts._sum.sellerNetCents ?? 0,
    feesCents: fees._sum.feeCents ?? 0,
  };
}
